name: Rust

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test-zk-prover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Zk Prover
        run: |
          cd prover
          cargo test --release --features dev-graph -- --nocapture

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test backend
        run: |
          cd backend
          cargo test --release -- --nocapture

  test-backend-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test backend example
        run: |
          cd backend
          cargo run --release --example summa_solvency_flow
