name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      run: |
        cd zk_prover
        cargo build --verbose
    - name: Format
      run: |
        cd zk_prover
        cargo fmt
    - name: Install Solidity
      run: |
        sudo add-apt-repository ppa:ethereum/ethereum
        sudo apt-get update
        sudo apt-get install solc

    - name: Run tests
      run: |
        cd zk_prover
        cargo test --release --features dev-graph -- --nocapture
