name: Rust

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install solc
        run: (hash svm 2>/dev/null || cargo install --version 0.2.23 svm-rs) && svm install 0.8.20 && solc --version

      - name: Test Zk Prover
        run: |
          cd zk_prover
          cargo test --release --features dev-graph -- --nocapture

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Test backend
        env:
          SIGNATURE_VERIFICATION_MESSAGE: "Summa proof of solvency for CryptoExchange"
        run: |
          cd backend
          cargo test --release -- --nocapture
